language: node_js

cache: false

node_js:
  - '10'
  - '12'

os:
  - linux
  - osx
  - windows

install:
  - yarn install --frozen-lockfile --network-timeout 1000000

script:
  - yarn run build
  - yarn run test:node

jobs:
  include:
    - stage: check
      script:
        - yarn run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script:
        - yarn run build
        - yarn run test:web

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script:
        - yarn run build
        - yarn run test:web -- --browsers FirefoxHeadless

notifications:
  email: false
