language: node_js

cache: false

node_js:
  - '10'
  - '12'

os:
  - linux
  - osx
  - windows

install:
  - yarn install --frozen-lockfile --network-timeout 1000000

script:
  set -e;
  yarn run lint;
  yarn run build;
  yarn run test
